Resolves https://github.com/TotalFreedom/TotalFreedomMod/issues/266
TotalFreedom/TotalFreedomMod pull request #1493
Opened 2016-02-12 20:34 UTC by LegendIsAwesomes

Resolves https://github.com/TotalFreedom/TotalFreedomMod/issues/266

2016-02-12 20:50 UTC, MrImmaculate commented on src/me/StevenLawson/TotalFreedomMod/Listener/TFM_PlayerListener.java
> +                if (effect.getType() == PotionEffectType.INVISIBILITY && !TFM_AdminList.isSuperAdmin(event.getPlayer()))
It is better to avoid nested if statements.

2016-02-12 20:54 UTC, AvalancheYT commented
Invisible is allowed.

2016-02-12 20:55 UTC, LegendIsAwesomes commented
@AvalancheYT the issue is accepted, so your wrong.

2016-02-12 20:58 UTC, LegendIsAwesomes commented
@MrImmaculate There. I fixed the nested if statements.

2016-02-12 22:27 UTC, AvalancheYT commented
@LegendIsAwesomes, according to our server rules & conduct policy, invisible is allowed.
```e. Players can use invisibility although admins may sometimes remove it in mass (inc. /invis smite) for security purposes.```

Read more: http://totalfreedom.boards.net/thread/21065/server-rules-conduct-policy-everybody#ixzz3zzlpfH1M

2016-02-12 23:14 UTC, LegendIsAwesomes commented
I don't care; I'm doing what the issue says.

2016-02-13 20:16 UTC, Wild1145 commented
I think you might have misunderstood the aim of the issue. The aim was to allow only admins to access game mode 3, not to block inis...

2016-02-13 21:23 UTC, MrImmaculate commented
@Wild1145 is correct. Please append this PR according to the issue.

2016-02-13 21:34 UTC, LegendIsAwesomes commented
Ahh okay, Will fix.

2016-02-21 13:18 UTC, LegendIsAwesomes commented
@JeromSar was @Wild1145 right?

2016-02-26 20:38 UTC, JeromSar commented
@LegendIsAwesomes He is partially right. He is referring to another issue. This PR should address /invis, a command for admins

2016-02-26 20:44 UTC, LegendIsAwesomes commented
@JeromSar I agreed to the CLA.

2016-02-26 20:44 UTC, JeromSar commented
@LegendIsAwesomes Great!

2016-11-13 00:25 UTC, Wild1145 reviewed
This PR now requires testing. At a glance it looks good.

2017-04-19 17:11 UTC, Wild1145 requested changes
Merge conflicts.

2017-06-09 16:10 UTC, Wild1145 requested changes

2017-06-09 16:10 UTC, Wild1145 commented on CONTRIBUTING.md
> +Visit [the wiki page](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing) to see the contributing guidelines.
Please revert this change.

2017-06-10 21:09 UTC, Commodore64x commented
@Wild1145 This can be closed as well, it doesn't resolve the issue given and is made for TFM 43

2017-06-10 22:01 UTC, Wild1145 commented
This one I will leave open until another PR with the same functionality has been merged, as this could still be rebased to work.

2017-06-10 22:09 UTC, Commodore64x commented
But @Wild1145 , this doesn't help the server at all, it literally blocks the invis potion

2017-06-10 22:12 UTC, Wild1145 commented
Okay, I've had a look through the associated issues and the ones that then have superseded it. Currently #856 is the issue this should have resolved. The scope of the original issue has been changed, and this PR would no longer resolve the associated issue. Given also that rules have been changed around invis, I would agree and will close this PR.

2017-06-10 22:12 UTC, closed without merging