Created Command /announce
TotalFreedom/TotalFreedomMod pull request #1645
Opened 2016-05-09 22:11 UTC by GX2H912

I have recently made a command that is /announce , and it should be used for broadcasting messages.

2016-05-09 22:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1645) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1645) before we can accept your contribution.<br/>

2016-05-10 06:19 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        FUtil.bcastMsg(String.format("[§5[§eTotalFreedom§5] §b:%s] %s", sender.getName(), message));
Maybe use the prefix announcement from ```config.yml```

2016-05-10 11:16 UTC, GX2H912 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        FUtil.bcastMsg(String.format("[§5[§eTotalFreedom§5] §b:%s] %s", sender.getName(), message));
Thanks for the comment, I have added it.

2016-05-10 11:41 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        FUtil.bcastMsg(String.format("[§5[§eTotalFreedom§5] &b", message));
Perhaps, you didn't understand me. I meant like use String to take the announcement prefix from ```config.yml```

2016-05-10 13:08 UTC, GX2H912 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        FUtil.bcastMsg(String.format("[§5[§eTotalFreedom§5] &b", message));
I will keep it as is, I think it is fine the way it is

2016-05-10 13:30 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        FUtil.bcastMsg(String.format("[§5[§eTotalFreedom§5] &b", message));
Other people uses this plugin... Don't forget.

2016-05-10 18:09 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        FUtil.bcastMsg(String.format("[§5[§eTotalFreedom§5] &b", message));
This is not suitable. You need to use the announcement prefix as defined by the config.yml

2016-05-10 18:10 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +            return false;
This should also return an error message, right now the user would have no idea what is happening and the reason that the command did nothing.

2016-05-10 21:34 UTC, GX2H912 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        FUtil.bcastMsg(String.format("[§5[§eTotalFreedom§5] &b", message));
Do you need me to add the announcement prefix string which points directly to the ConfigEntry?

2016-05-11 06:44 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        TFM_Util.bcastMsg(TFM_ConfigEntry.ANNOUNCER_PREFIX.getString().replaceAll("&", "§") + message);
TFM_Config don't exist. Use MainConfig.get(ConfigEntry.{Name}, {type}.class);

2016-05-11 19:30 UTC, GX2H912 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        TFM_Util.bcastMsg(TFM_ConfigEntry.ANNOUNCER_PREFIX.getString().replaceAll("&", "§") + message);
But ConfigEntry does exist. Does it not?

2016-05-11 21:39 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        TFM_Util.bcastMsg(TFM_ConfigEntry.ANNOUNCER_PREFIX.getString().replaceAll("&", "§") + message);
Perhaps, you haven't tested it yet....

2016-05-11 22:21 UTC, ItzLevvie commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +@CommandParameters(description = "Allows Super Administrators to announce messages.", usage = "/<command> <message...>", aliases = "ae")
Might want to change that?

2016-05-11 22:45 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_announce.java
> +        TFM_Util.bcastMsg(TFM_ConfigEntry.ANNOUNCER_PREFIX.getString().replaceAll("&", "§") + message);
There is also a TFM colourise option that you should really use instead of that replaceable...

2016-05-13 12:36 UTC, GX2H912 commented
Someone, please delete this. Prozza already made an announce command 17 hours ago.

2016-05-14 11:05 UTC, JeromSar commented
@GX2H912 You cannot delete PRs or issues.

2016-11-13 00:15 UTC, Wild1145 requested changes
Changes that were mentioned previously need addressing before this PR can be merged.

2016-12-18 22:42 UTC, closed without merging