Resolves #1753 Disable written books
TotalFreedom/TotalFreedomMod pull request #1755
Opened 2016-06-08 00:11 UTC by CreeperSeth

This resolves #1753 This will stop players from opening written books, thus putting an end to book exploits and crash books. This has been a major problem for a while now.

2016-06-08 00:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1755) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1755) before we can accept your contribution.<br/>

2016-08-16 08:21 UTC, Mafrans commented
I have already created a patch for fixing exploit books into DaedalusMod, thus a change like this is not needed.

2016-08-17 14:40 UTC, JeromSar commented
@Mafrans DaedalusMod is actually more of a temporary workaround to long-term features that can not (yet) be implemented in TFM. Ideally all functionality should be incorporated in TFM.

2016-08-19 14:01 UTC, Wild1145 commented
Also, your addition to DaedalusMod is not in the production Github branch so as @JeromSar said it does need to be added here because when I push the next update to DaedalusMod your changes will not be there unless appropriate PR's have been opened on there as instructed.

2016-11-13 00:31 UTC, Wild1145 reviewed
Looks good, just needs testing to make sure its 100%

2017-01-28 20:25 UTC, Commodore64x commented
Yeah this is a cheap and nasty fix. What about /kit color? I used it alot until Mafrans added a anti-json book component into his NoSploit. This issue is a duplicate of what has already been fixed. @Wild1145 Close it?

2017-01-28 20:34 UTC, Wild1145 commented
@Commodore64x Where has this been fixed?

2017-01-29 09:41 UTC, OxLemonxO commented
@Wild1145 it has been fixed here:
https://github.com/Mafrans/NoSploit/blob/master/src/main/java/me/mafrans/nosploit/listeners/BookPatch.java

2017-01-29 15:34 UTC, Wild1145 commented
@OxLemonxO Plugins Like NoSploit should be treated as temporary, and any available and wanted functionality ported into TotalFreedomMod as early as possible.

2017-04-19 17:19 UTC, Wild1145 requested changes
Merge conflicts.

2017-06-10 10:53 UTC, Commodore64x commented
@Wild1145 This is no longer needed, book exploits were patched ages ago.

2017-06-10 10:56 UTC, Wild1145 commented
@Commodore64x Where were they patched though?

2017-06-10 11:09 UTC, mayokek commented
@Wild1145, close? By the look of it, the creator had deleted the repo.

2017-06-10 11:10 UTC, Wild1145 commented
@mayokek So they have.

2017-06-10 11:10 UTC, closed without merging