block summon
TotalFreedom/TotalFreedomMod pull request #1792
Opened 2016-07-21 21:09 UTC by notanoperator

2016-07-21 21:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1792) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1792) before we can accept your contribution.<br/>

2016-07-21 22:42 UTC, Wild1145 commented
What issue does this resolve?

2016-07-21 23:25 UTC, notanoperator commented
In reply to Wild - https://github.com/TotalFreedom/TotalFreedomMod/issues/1791

2016-07-25 15:45 UTC, LegendIsAwesomes commented
Please read the contributing guidelines: https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing , as this is just a small config edit and therefore is against the contributing guidelines as it clearly states, in the words of Jerom (Prozza), thank you for contributing.

2016-07-26 10:13 UTC, JeromSar commented on src/main/resources/config.yml
> +  - 'n:b:/summon:This command has been blocked for security reasons'
I think this should just be an empty '_' message. Since most of these commands are blocked for "security measures". The empty message implies this.

2016-11-13 00:33 UTC, Wild1145 requested changes
Please make the changes addressed earlier before this PR can be merged.

2016-12-25 09:28 UTC, closed without merging