add the adminhelp command
TotalFreedom/TotalFreedomMod pull request #1810
Opened 2016-08-08 20:03 UTC by notanoperator

when /report can't always be used

2016-08-08 20:14 UTC, notanoperator commented
<img src=http://imgur.com/Oi9r4cM></img>
Works, and compiles

2016-08-09 09:24 UTC, DUFCLiam commented
You forgot the `.java` extension on the `C_adminhelp` class.

2016-08-09 10:17 UTC, OxLemonxO commented
Incorrect formatting.

2016-08-16 08:14 UTC, Mafrans commented
Why is this needed, we already have /report and noone will be using it anyways.

2016-08-18 01:28 UTC, notanoperator commented
@mafrans did you even try reading the issue? smh

2016-08-18 12:30 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/ChatManager.java
> +         public void adminHelp(Player sender, String message) {
Formatting.

2016-08-18 12:31 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_adminhelp.java
> +            if (args.length < 1) {
Formatting, and why the extra new lines?

2016-08-18 12:31 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_adminhelp.java
> +    Player player = (Player) sender;
Just use playerSender..

2016-08-18 12:31 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_adminhelp.java
> +        String message = StringUtils.join(ArrayUtils.subarray(args, 0, args.length), " ");
Formatting.

2016-08-22 18:07 UTC, Wild1145 commented
You have deleted all your changes... There are no longer any file changes to this PR.

2016-08-24 00:32 UTC, notanoperator commented
@Wild1145 fixed idk why i removed that...

2016-11-13 00:35 UTC, Wild1145 requested changes
Please address this and the earlier changes requested.

2016-11-13 00:35 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/ChatManager.java
> +                playerMsg(player, ChatColor.RED + "[ADMINHELP] " + ChatColor.GOLD + sender.getName() + ": " + message);
Im concerned that the gold may get confused with the new admin chat colour. Can this be changed to another colour? Dark Blue or a light red maybe?

2016-12-25 09:29 UTC, closed without merging