Add name history command - Adds #900
TotalFreedom/TotalFreedomMod pull request #1847
Opened 2016-08-28 11:01 UTC by OxLemonxO

Adds #900

2016-08-28 11:21 UTC, OxLemonxO commented
You have to use the latest username of the player- Can't use an earlier username.

2016-09-05 06:02 UTC, PacksGamingHD commented
Tested on my server and it works

2016-09-07 20:52 UTC, Wild1145 commented
The related issue is for the 5.2 release, I have placed this PR on hold and it can be re-reviewed when we have completed work on the 5.1 release.

2016-10-11 15:04 UTC, OxLemonxO commented
@JeromSar

2016-10-11 15:04 UTC, OxLemonxO commented
Oops I accidently closed it

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +                        sender.sendMessage(ChatColor.RED + "Player not found!");
As the Bukkit API is not thread safe, you cannot call this method asynchronously. You have to resynchronise with the server first.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +                DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
Seems like something that should be a field, probably static and final.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +class FName implements Comparable<FName>
Does this compile? I am sure you cannot have two classes in one file. Either way. Declare public/private.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/UUIDFetcher.java
> +class FetchedUuid
Once again, is this possible? Declare private/public.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/UUIDFetcher.java
> +    String id;
This field should probably be final, and should be private or public.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +                        FLog.severe(ex);
When catching this, should probably send a message to the CommandSender as well, to notify them something went wrong.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +        else
return, instead of else block?

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +    public String name;
This field has a getter, so this should probably be private.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +    public long changedToAt;
This field has no getter, but should probably have one. This means that this should probably be a private field.

2016-10-11 21:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +                        printHistory(sender, oldNames);
As the Bukkit API is not thread safe, you cannot call this method asynchronously. You have to resynchronise with the server first.

2016-10-11 21:08 UTC, JeromSar commented
Looks good, but needs some changes, see above.

2016-10-12 10:40 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +class FName implements Comparable<FName>
You can have more then two classes in one file. MainConfig does this for the ConfigDefaults class.

2016-10-12 14:28 UTC, OxLemonxO commented
Fixed @JeromSar

2016-10-12 20:39 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +class FName implements Comparable<FName>
Prett sure those are nested static classes, and not seperate classes.

2016-10-12 20:42 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +        Player player = Bukkit.getPlayer(sender.getName());
This does not work when the CommandSender is a console. Instead, perhaps change `FSync.playerMsg()` to take a CommandSender as an argument?

2016-10-12 20:42 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +                uuid = UUIDFetcher.fetch(username);
Might as well declare uuid here, as the declaration above has no other purpose.

2016-10-12 20:43 UTC, JeromSar requested changes
Please change the PR to reflect the comments above and below.

2016-10-12 20:45 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +    public static DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
Perhaps this should be final?

2016-10-12 20:45 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/UUIDFetcher.java
> +    public final String id;
Perhaps this needs a getter.

2016-10-13 02:24 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +class FName implements Comparable<FName>
Well, it compiles, and I tested it on my server, and it works.

2016-10-13 02:25 UTC, OxLemonxO commented
Done changes @JeromSar

2016-10-13 05:35 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +    public static void reportHistory(final CommandSender sender, final String username
You are missing another parentheses.

2016-10-15 16:48 UTC, OxLemonxO commented
@HeromSar?

2016-10-23 01:24 UTC, PacksGamingHD commented
I was able to test lemons latest code pushed and it all works

2016-11-09 09:26 UTC, JeromSar approved these changes

2016-11-09 09:27 UTC, JeromSar commented
@OxLemonxO Testing this ASAP. merging when tested.

2017-01-26 17:00 UTC, OxLemonxO commented
Bump?

2017-01-26 17:19 UTC, JeromSar commented
Debump.

2017-05-10 17:04 UTC, Wild1145 commented
Currently not building https://travis-ci.org/Wild1145/TotalFreedomMod/builds/230516942?utm_source=github_status&utm_medium=notification

2017-05-14 00:48 UTC, Wild1145 commented
Automated builds are now working again.

2017-05-29 19:12 UTC, JeromSar requested changes

2017-05-29 19:12 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/UUIDFetcher.java
> +class FetchedUuid
Declare public please.

2017-05-29 19:12 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +class FName implements Comparable<FName>
Please convert this to a nested static class.

2017-05-29 23:00 UTC, OxLemonxO commented
Converted, @JeromSar

2017-05-30 06:07 UTC, JeromSar requested changes
Just small changes now, and then we can test, and if all is well, merge.

2017-05-30 06:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/UUIDFetcher.java
> +    static class FetchedUuid
Needs to be either private or public

2017-05-30 06:07 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/util/History.java
> +    static class FName implements Comparable<FName>
Needs to be either private or public.

2017-05-30 07:42 UTC, OxLemonxO commented
Changes added @JeromSar

2017-05-30 10:00 UTC, Wild1145 commented
Currently building on TravisCI https://travis-ci.org/Wild1145/TotalFreedomMod/builds/237411850?utm_source=github_status&utm_medium=notification

2017-05-30 10:04 UTC, JeromSar approved these changes

2017-05-30 10:04 UTC, JeromSar commented
Just testing now.

2017-05-30 10:05 UTC, Wild1145 approved these changes
Build Passing TravisCI Tests

2017-05-31 08:16 UTC, Wild1145 submitted a review, later dismissed
There appear to be merge conflicts with the base branch now

2017-05-31 13:48 UTC, OxLemonxO commented
Resolved conflicts.

2017-05-31 13:50 UTC, JeromSar commented
Ouch, this will not go over well. The main development branch is currently `tfm5.1-mc1.12`. Syncing with `server` will cause problems.

2017-05-31 13:52 UTC, Wild1145 commented
@OxLemonxO Might want to revert the previous commit?

2017-05-31 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1847) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1847) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: OxLemonxO<br/>:white_check_mark: marcocorriero<br/>:x: StevenLawson<br/><hr/>**marcocorriero** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TotalFreedom/TotalFreedomMod?pullRequest=1847) it.</sub>

2017-05-31 14:20 UTC, OxLemonxO commented
Reverted.

2017-09-20 21:15 UTC, marcocorriero commented
Tested, is broken.

2017-09-21 08:34 UTC, OxLemonxO commented
@marcocorriero in which way?

2017-09-23 05:52 UTC, Telesphoreo commented
Fails for me also.
```[01:51:04 WARN]: [Fuse] Plugin Fuse v1.5 generated an exception while executing task 6
java.lang.NullPointerException: null
        at com.fusenetworks.fuse.util.UUIDFetcher.fetch(UUIDFetcher.java:47) ~[?:?]
        at com.fusenetworks.fuse.util.History$1.run(History.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]```

Thats what it is when implemented into Fuse

2017-09-23 12:51 UTC, Wild1145 commented
TravisCI doesn't appear to be kicking in for some reason... Apparently also needs the CLA?

2017-09-23 13:07 UTC, OxLemonxO commented
I've done CLA - no idea why it needs it again.

2017-09-23 13:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1847) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1847) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: OxLemonxO<br/>:white_check_mark: marcocorriero<br/>:x: StevenLawson<br/><hr/>**marcocorriero** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TotalFreedom/TotalFreedomMod?pullRequest=1847) it.</sub>

2017-09-23 13:10 UTC, OxLemonxO commented
Errors fixed.

2017-09-23 15:58 UTC, Wild1145 commented
Because @StevenLawson has a commit in the PR he will need to sign the CLA before the check passes.

2017-09-24 05:13 UTC, Telesphoreo commented
Still doesn't seem to work for me. It's now saying that it can't find the URL or something
```[01:12:25 ERROR]: null
java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_131]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_131]
        at com.fusenetworks.fuse.util.UUIDFetcher.fetch(UUIDFetcher.java:38) [Fuse.jar:?]
        at com.fusenetworks.fuse.util.History$1.run(History.java:31) [Fuse.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

2017-10-15 04:29 UTC, Telesphoreo commented
Still gives this error
```[00:28:08 INFO]: [PLAYER_COMMAND] Telesphoreo (Telesphoreo): /namehistory Telesphoreo
[00:28:08 ERROR]: null
java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_131]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_131]
        at com.fusenetworks.fuse.util.UUIDFetcher.fetch(UUIDFetcher.java:38) [Fuse.jar:?]
        at com.fusenetworks.fuse.util.History$1.run(History.java:31) [Fuse.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

2019-09-14 19:07 UTC, Wild1145 commented
Thank you for your contribution. Sadly we have decided to close this issue as there has been no recent activity to this pull request. If you wish to continue working on this PR please re-open the issue and ensure that all requested changes are made.

2019-09-14 19:07 UTC, closed without merging