Create /getgamemode
TotalFreedom/TotalFreedomMod pull request #1855
Opened 2016-09-03 14:25 UTC by notanoperator

Fixes #1839 
Get's players gamemode.

2016-09-03 14:49 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +       if (args.length < 1) {
Formatting.

2016-09-03 14:49 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +       if (player == null) {
Formatting.

2016-09-03 14:49 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +    return true;
Formatting.

2016-09-03 14:50 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +
Useless extra line.

2016-09-03 15:50 UTC, CrafterSmith12 commented
Just do /who (player)

2016-09-03 22:19 UTC, notanoperator commented
"Needs Testing" "Needs Changes"
Codes fine.
Works fine.

2016-09-03 22:37 UTC, AvalancheYT commented
You'll need to fix the formatting as said above.

2016-09-07 20:50 UTC, Wild1145 commented
As the issue has not yet been accepted or assigned a milestone this PR is also on hold until further notice.

2016-09-21 14:02 UTC, Superior-tL commented
Just use /who (player)...

2016-10-19 21:29 UTC, Wild1145 requested changes
Please address the formatting issues raised within the inline comments.

2017-04-19 17:25 UTC, Wild1145 commented
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

2017-04-19 17:25 UTC, closed without merging