Resolves #1883 - Purging Squids
TotalFreedom/TotalFreedomMod pull request #1929
Opened 2016-11-26 12:14 UTC by AvalancheYT

2016-11-26 22:29 UTC, Commodore64x commented
Yes, this works, have tested before.

2016-11-26 22:31 UTC, ghost approved these changes
Simple code change, I have tested this and it works, approved.

2016-12-03 05:17 UTC, PacksGamingHD commented
@Commodore64x, "Only those with write access to this repository can merge pull requests.". You can just approve something

2016-12-03 07:56 UTC, Commodore64x commented
@PacksGamingHD I didn't try to merge it... Notice how I approved it lmao... I don't understand your comment in relation to my most recent post.

2016-12-03 07:58 UTC, AvalancheYT commented
@PacksGamingHD, he approved my changes and tested it. He knows that he can't merge it.

2016-12-03 19:49 UTC, PacksGamingHD commented
I’m aware. I’m just saying that it’s not his job to approve the PR's
> On Dec 2, 2016, at 11:58 PM, Nathan Curran <notifications@github.com> wrote:
> 
> Reopened #1929 <https://github.com/TotalFreedom/TotalFreedomMod/pull/1929>.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/TotalFreedom/TotalFreedomMod/pull/1929#event-880904782>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AG8rNR3OXZEYpMb7-OCxl3_3NfRYU3HDks5rESExgaJpZM4K84ZG>.
>

2016-12-03 21:27 UTC, Commodore64x commented
Packs I have only approved the code because I reviewed it and found no errors, I am not approving it for merge, etc.

2016-12-03 22:59 UTC, PacksGamingHD commented
But you can’t approve anything
> On Dec 3, 2016, at 1:27 PM, Commodore64x <notifications@github.com> wrote:
> 
> Packs I have only approved the code because I reviewed it and found no errors, I am not approving it for merge, etc.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/TotalFreedom/TotalFreedomMod/pull/1929#issuecomment-264666624>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AG8rNVYfv5RVYmu9NjyPEaYG7uZOlZx0ks5rEd67gaJpZM4K84ZG>.
>

2016-12-03 23:46 UTC, AvalancheYT commented
@PacksGamingHD, do a review on the code changes and see.

2016-12-04 00:04 UTC, PacksGamingHD commented
I’m aware that they work, but Jerom is the one who has the power to accept PRs. Unless I’ve been under a rock and you’ve suddenly become TFM devs or GitHub moderators
> On Dec 3, 2016, at 3:46 PM, Nathan Curran <notifications@github.com> wrote:
> 
> @PacksGamingHD <https://github.com/PacksGamingHD>, do a review on the code changes and see.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/TotalFreedom/TotalFreedomMod/pull/1929#issuecomment-264673603>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AG8rNR8IRKJv-8_ta6R1r-5VtrOgZFeHks5rEf9kgaJpZM4K84ZG>.
>

2016-12-04 00:04 UTC, ghost requested changes
<Removed by Github Moderator>

2016-12-04 00:08 UTC, ghost requested changes
Changes requested.

2016-12-04 00:08 UTC, Commodore64x commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_mobpurge.java
> +                if (ent instanceof Creature || ent instanceof Ghast || ent instanceof Slime || ent instanceof EnderDragon || ent instanceof Ambient || ent instanceof Squid)
Replace ent instanceof Squid with ent instanceof WaterMob

2016-12-04 00:08 UTC, Commodore64x commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_mobpurge.java
> +import org.bukkit.entity.Squid;
Add import org.bukkit.entity.WaterMob and removed org.bukkit.entity.Squid

2016-12-04 02:56 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_mobpurge.java
> +import org.bukkit.entity.Squid;
Does it work?

2016-12-04 02:56 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_mobpurge.java
> +                if (ent instanceof Creature || ent instanceof Ghast || ent instanceof Slime || ent instanceof EnderDragon || ent instanceof Ambient || ent instanceof Squid)
Read my comment above.

2016-12-05 03:34 UTC, Commodore64x commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_mobpurge.java
> +import org.bukkit.entity.Squid;
Yes it does, it finds all watermobs not just squid.

2016-12-05 03:36 UTC, AvalancheYT commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_mobpurge.java
> +import org.bukkit.entity.Squid;
Okay, I will make the changes tonight and test it.

2016-12-20 21:37 UTC, Commodore64x commented
Add the needs changes tag please @Wild1145

2017-01-16 17:35 UTC, Pramire commented
Needs review @JeromSar

2017-01-16 18:42 UTC, Wild1145 commented
@Pramire This has been reviewed and is awaiting changes, it will be reviewed again when the changes are made. You do not need to bump the issue.

2017-01-16 18:47 UTC, Wild1145 requested changes
Please make the changes that @Commodore64x has suggested. This should then be in a position to be tested and merged.

2017-01-16 23:47 UTC, AvalancheYT commented
Testing watermobs now.

2017-01-17 00:08 UTC, AvalancheYT commented
Okay, latest change have been made on request. Tested and the code is working.

2017-01-17 18:39 UTC, Wild1145 approved these changes

2017-05-31 07:18 UTC, Wild1145 commented
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

2017-05-31 07:18 UTC, closed without merging