Add ability for logs to be downloaded. Adds #1968
TotalFreedom/TotalFreedomMod pull request #1969
Opened 2017-02-09 12:36 UTC by OxLemonxO

This adds the ability for logs to be downloaded via the HTTPD.

2017-02-09 20:46 UTC, Wild1145 requested changes

2017-02-09 20:46 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_logfile.java
> +            return HTMLGenerationTools.paragraph("Can't find the logs folder.");
Should this not also log out as an error to the server?

2017-02-09 20:46 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_logfile.java
> +                    out.append(HTMLGenerationTools.paragraph("Log files access denied: Your IP, " + remoteAddress + ", is not registered to a superadmin on this server."));
This should also be logged server side as well to keep a log of who is attempting to access the logs.

2017-02-09 20:46 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_logfile.java
> +                    out.append(HTMLGenerationTools.paragraph("Log files access denied: Your IP, " + remoteAddress + ", is not registered to a superadmin on this server."));
Once again this should be logged to the server console as well.

2017-02-10 04:32 UTC, OxLemonxO commented
It now logs it to the server console too.

2017-02-10 16:01 UTC, Wild1145 approved these changes

2017-02-11 00:27 UTC, Commodore64x commented
You can already download logs via HTTPD @OxLemonxO ....

2017-02-11 04:35 UTC, OxLemonxO commented
@Commodore64x No, can you download it like this?
http://i.imgur.com/nZTy5t9.png

2017-02-23 13:52 UTC, marcocorriero commented
but it will need to be wiped every week to free space for server?

2017-02-23 14:04 UTC, OxLemonxO commented
....... @marcocorriero, all the files that are stored in /logs are simply just listed and download links are shown

2017-05-29 19:05 UTC, JeromSar requested changes

2017-05-29 19:05 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_logfile.java
> +            FLog.warning("The logfile module failed to find the logs folder.");
Unreachable code.

2017-05-29 19:05 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_logfile.java
> +                    FLog.info("An unregistered IP (" + remoteAddress ") has tried to access the log files");
This is not valid Java, I believe.

2017-05-29 19:05 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_logfile.java
> +                    FLog.info("An unregistered IP (" + remoteAddress ") has tried to download a log file");
This is not valid Java, I believe.

2017-05-30 07:43 UTC, OxLemonxO commented
Fixed @JeromSar

2017-05-30 08:25 UTC, JeromSar approved these changes

2017-05-30 09:00 UTC, JeromSar commented
Just needs testing now. :)

2019-09-14 19:28 UTC, Wild1145 commented
Tested and happy. One minor typo which I've pushed a fix for. Merging as resolved. Thanks for the contribution @OxLemonxO and apologies it's taken so long for me to get around to merging this.

2019-09-14 19:29 UTC, merged