Added some commands to the blacklist
TotalFreedom/TotalFreedomMod pull request #1994
Opened 2017-04-08 20:17 UTC by DarkGamingDronze

To block any admin abuse.

2017-04-08 20:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1994) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=1994) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TotalFreedom/TotalFreedomMod?pullRequest=1994) it.</sub>

2017-04-09 11:03 UTC, Wild1145 commented
Thank you for contributing to the project, could you please amend your opening message to include the issue that this PR resolves. Thank You.

2017-04-09 20:34 UTC, DarkGamingDronze commented
I do not hnderstand you. Please explain what you mean - I am new and this is my first pull request ever since the new tfm came out.

2017-04-09 21:34 UTC, Wild1145 commented
@DarkGamingDronze Take a look at the Contributing Guidelines, that should explain everything you need to know.

2017-04-18 18:24 UTC, DarkGamingDronze commented
Says all checks have passed

Bump

2017-04-19 16:41 UTC, Wild1145 commented
@DarkGamingDronze This currently does not meet the Contributing guidelines, please see my earlier comment.

2017-05-04 08:11 UTC, DarkGamingDronze commented
@Wild1145, I have fixed it now. Sorry for the long time.

2017-05-04 18:28 UTC, Wild1145 commented
@DarkGamingDronze It still requires a issue number, like #1234 for the issue that was created.

2017-06-10 11:53 UTC, Wild1145 requested changes
Minor cosmetic change requested.

2017-06-10 11:53 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_wildcard.java
> +            msg("Did you really think that was going to work? What where you thinking?", ChatColor.RED);
Probably would change this message all together myself. More along the lines of "Sorry that command cannot be used with the Wildcard command. Please try something else"

2017-06-11 16:12 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_wildcard.java
> +            msg("Did you really think that was going to work? What where you thinking?", ChatColor.RED);
Originally just @StevenLawson's humor there. :)

2018-01-26 21:58 UTC, Wild1145 approved these changes

2018-05-24 22:08 UTC, Wild1145 commented
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

2018-05-24 22:08 UTC, closed without merging