Configuration File Sync
TotalFreedom/TotalFreedomMod pull request #2002
Opened 2017-04-21 14:07 UTC by Wild1145

This brings the config file back in Sync (Nearly) with what is on the server currently, less any current patches that TFM does not support.

2017-04-21 15:15 UTC, ItzLevvie commented on src/main/resources/config.yml
> +  - 's:b:/summon:Do to security reasons, the use of /summon has been disabled.'
This should be ```Due to ...``` instead of ```Do to ...``` 

The same thing also goes for line 129

2017-04-22 21:55 UTC, Wild1145 commented on src/main/resources/config.yml
> +  - 's:b:/summon:Do to security reasons, the use of /summon has been disabled.'
This is simply the current config on the server. I will advise Mark that the corrections are needed, once he makes the change I will update this PR with the change.

2017-06-02 10:47 UTC, mayokek commented
@Wild1145, this PR is conflicting. Might wanna fix that.

2017-06-02 12:27 UTC, JeromSar commented
@mayokek It might not be, this PR does not target the development branch.

2017-06-02 12:32 UTC, mayokek commented
@JeromSar oh, okay.

2017-06-13 09:19 UTC, JeromSar approved these changes

2017-06-30 07:45 UTC, JeromSar requested changes

2017-06-30 07:45 UTC, JeromSar commented on src/main/resources/config.yml
> +  - 151.50.73.196
These should not be synced with the server. They should remain the config default

2017-07-01 12:58 UTC, Wild1145 commented
This was what was sent to me, I am no longer in a position to get the latest version of this now anyway, so would advise this being re-synced with a more up to date version given how old this PR now is.

2017-07-01 12:58 UTC, closed without merging