Added /Verified
TotalFreedom/TotalFreedomMod pull request #2011
Opened 2017-05-23 13:52 UTC by GracieWargo

Sometimes after an admin has verified, they have a hard time get the attention of other admins... This command let's the other know they have verified and are requesting to be added.

2017-05-23 13:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=2011) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TotalFreedom/TotalFreedomMod?pullRequest=2011) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TotalFreedom/TotalFreedomMod?pullRequest=2011) it.</sub>

2017-05-23 18:22 UTC, marcocorriero commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_verified.java
> +        FUtil.bcastMsg(ChatColor.GRAY + "[" + ChatColor.YELLOW + "Imposter" + ChatColor.GRAY + "] "
Why bcast when it can be sent to Admins only?

Ops could use it to spam.

2017-05-23 18:22 UTC, marcocorriero commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_verified.java
> +@CommandPermissions(level = Rank.IMPOSTOR, source = SourceType.BOTH)
Rank impostor = OP , is the same thing.

2017-05-23 18:23 UTC, marcocorriero commented
You should add a filter for the command using the impostor system to make sure if the OP is logged as Impostor.

2017-05-23 19:11 UTC, marcocorriero commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_verified.java
> +            FUtil.bcastMsg(ChatColor.GRAY + "[" + ChatColor.YELLOW + "Imposter" + ChatColor.GRAY + "] "
Still Futil.bcastmsg means Public chat, you should get the code from /report ;)

2017-05-24 19:11 UTC, Wild1145 commented
Thank you for contributing to the project, could you please amend your opening message to include the issue that this PR resolves. Thank You.

2017-05-25 17:58 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_verified.java
> +@CommandPermissions(level = Rank.IMPOSTOR, source = SourceType.BOTH)
@marcocorriero Not quite, as the terms imply, rank `IMPOSTOR` is available to non-op players.

2017-06-10 11:51 UTC, Wild1145 commented
Would probably suggest actually sending this to only admins (Perhaps in admin chat?) and also having it setup so it can only be executed once per player. Maybe even adding an option for the admin running the command to define where they verified (as I for example used to always verify in Discord, or get admins to PM me on the forums, where a lot of others just use the shout box)

2017-06-10 11:51 UTC, Wild1145 requested changes
Some minor formatting changes, but also see my other comment in the main thread.

2017-06-10 11:51 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_verified.java
> +
Little thing, but please remove the additional line.

2017-06-10 11:51 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_verified.java
> + {
Formatting here is weird as well

2018-01-26 21:59 UTC, Wild1145 commented
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

2018-01-26 21:59 UTC, closed without merging