Increased text limit - Resolves #1941
TotalFreedom/TotalFreedomMod pull request #2039
Opened 2017-05-31 10:44 UTC by Wild1145

2017-05-31 13:43 UTC, JeromSar requested changes

2017-05-31 13:43 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/ChatManager.java
> +        if (message.length() > 250)
As per [the Minecraft wiki page](http://minecraft.gamepedia.com/1.11), the maximum length should be 256.

2017-05-31 13:45 UTC, Wild1145 commented
@JeromSar Was not aware, the original issue has been updated and I'll update the PR shortly.

2017-06-02 13:27 UTC, JeromSar approved these changes

2017-06-30 07:41 UTC, merged