Command Spy Persistace
TotalFreedom/TotalFreedomMod pull request #2040
Opened 2017-05-31 12:17 UTC by Wild1145

This resolves #785

2017-05-31 13:13 UTC, lemonsked requested changes

2017-05-31 13:13 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/CommandSpy.java
> +            } else
Formatting.

2017-05-31 13:13 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +    public boolean commandSpyIsActive{
Missing ()'s and { must be on next line.

2017-05-31 13:13 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/CommandSpy.java
> +        } else
Formatting.

2017-05-31 13:13 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/admin/AdminList.java
> +    public boolean setCommandSpyActive(boolean status, Player player){
{ on next line (formatting).

2017-05-31 13:13 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +        return commandSpyStatus
Missing semicolon.

2017-05-31 13:13 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/admin/AdminList.java
> +        else{
{ on next line (formatting).

2017-05-31 13:13 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_cmdspy.java
> +        } else
else on next line.

2017-05-31 13:14 UTC, Wild1145 commented
This is why you dont switch between IDE's...  Whoops

2017-05-31 13:27 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/admin/AdminList.java
> +        if (status == true)
you can just do if(status)

2017-05-31 13:28 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_cmdspy.java
> +        if (playerdata.cmdspyEnabled() == true)
== true is unneeded

2017-05-31 13:33 UTC, Wild1145 commented
@OxLemonxO There we are, mind taking a look for me now?

2017-05-31 13:35 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +
Extra whitespace

2017-05-31 13:36 UTC, lemonsked approved these changes

2017-05-31 13:36 UTC, JeromSar requested changes

2017-05-31 13:36 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +        cs.set("commandspy_isactive", commandSpyStatus);
How about just `commandspy`?

2017-05-31 13:36 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +
Unnecessary newline.

2017-05-31 13:36 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +    public boolean commandSpyIsActive()
Should probably be `hasCommandSpy()`

2017-05-31 13:36 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +    private boolean commandSpyStatus = true;
How about just `commandSpy`?

2017-05-31 13:36 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/AdminList.java
> +    public boolean isCommandSpyActive(Player player)
This method does to little. It is redundant and all dependent operations should probably inline any operations.

2017-05-31 13:36 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/AdminList.java
> +    public boolean setCommandSpyActive(boolean status, Player player)
As noted above, this method does too little.

2017-05-31 14:03 UTC, Wild1145 commented
@JeromSar Mind taking a look, I think I've found the best way now.

2017-05-31 14:21 UTC, lemonsked commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_cmdspy.java
> +        Admin admin = getAdmin((Player) sender);
use playerSender

2017-06-05 21:58 UTC, Commodore64x commented
This is completely uneeded code? FPlayer data is stored per server session not player session now ( this isn't on the github)

2017-06-05 22:35 UTC, mayokek commented
@Commodore64x, then make an issue about it and a PR.

2017-06-06 06:16 UTC, JeromSar requested changes

2017-06-06 06:16 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/CommandSpy.java
> +        if (plugin.al.isAdmin(event.getPlayer()))
This entire block should be changed to something like:
```java
boolean admin = plugin.al.isAdmin(event.getPlayer();
playerdata.setCommandSpy(admin && admin.hasCommandSpy());
```

2017-06-06 06:16 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/CommandSpy.java
> +                playerdata.setCommandSpy(playerdata.cmdspyEnabled());
This statement does nothing. Possibly a typo.

2017-06-06 06:16 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +    private Boolean commandSpy = true;
Should be a `boolean`.

2017-06-06 06:16 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +    public Boolean hasCommandSpy()
`commandSpy` does not need getters/setters. We have lombok for that.

2017-06-06 06:16 UTC, JeromSar commented on src/main/java/me/totalfreedom/totalfreedommod/admin/Admin.java
> +}
Missing newline.

2017-06-06 15:45 UTC, Wild1145 commented
I'll pull this into Netbeans soon and see whats gone wrong, IntelliJ hasnt really done a great job when I was at work by the looks of it. 

As for lombok, I've never heard of that before, so might not be so helpful there.

2017-08-13 13:00 UTC, OxLemonxO commented
Instead of making a new getter for `commandspy`, the annotation @Getter already created one.
You can use `isCommandSpy`

2017-08-13 13:37 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/CommandSpy.java
> +        if (plugin.al.isAdmin(event.getPlayer()))
Given I'm struggling to understand what that even does... I will leave the PR as is for now, its already broken and needs more work, but I can't see what I've screwed up.

2017-08-14 09:45 UTC, Commodore64x commented
This isn't actually needed, there is a one line code change that will fix a vast amount of issues.

2017-08-15 18:34 UTC, Wild1145 commented
@Commodore64x It however is not implemented at the current time. Until such a time that it is, this does resolve a valid and approved issue.

2026-01-13 15:51 UTC, closed without merging