Smite update, adds the sender.
TotalFreedom/TotalFreedomMod pull request #2073
Opened 2017-07-02 02:28 UTC by Savnith

https://github.com/TotalFreedom/TotalFreedomMod/issues/2032

2017-07-02 10:59 UTC, ItzLevvie commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +        }else {
Formatting

2017-07-02 11:41 UTC, lemonsked requested changes

2017-07-02 11:41 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +
Useless extra line

2017-07-02 11:41 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +            player.sendMessage(ChatColor.YELLOW + sender.getName() + " smited you for, " + reason);
the sender is already shown in the chat to all players.  don't  need to edit this.

2017-07-02 11:41 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +        player.sendMessage(ChatColor.YELLOW + "You've been smitten by: " + sender.getName());
Again, don;t need this  since the sender is already shown in the chat to all players.

2017-07-02 11:41 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +           FUtil.bcastMsg("Smited by: " + sender.getName(), ChatColor.RED);
`smitten` not `smited`

2017-07-02 11:41 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +            FUtil.bcastMsg("  Reason: " + reason + " (" + sender.getName() + ")", ChatColor.RED);
don't need sender twice.

2017-07-02 11:41 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +    public static void smite(Player player, CommandSender sender)
Pretty sure some other command/listener uses this method and that's why it's there. If you haven't updated the arg in the other class, it won't compile. Correct me if I'm wrong.

2017-07-03 08:53 UTC, Savnith commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +    public static void smite(Player player, CommandSender sender)
I tested it it caused a error without it.

2017-07-03 10:29 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +            player.sendMessage(ChatColor.YELLOW + "You where smitten for, " + reason);
were*

2017-07-03 22:48 UTC, mayokek commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +    public static void smite(Player player, CommandSender sender)
Lemon is correct.

2017-07-03 22:52 UTC, mayokek commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +
I believe this whitespace shouldn't be there.

2017-07-03 22:52 UTC, mayokek commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +            player.sendMessage(ChatColor.YELLOW + "You where smitten for, " + reason);
Were*

2017-07-04 00:47 UTC, Savnith commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +    public static void smite(Player player, CommandSender sender)
No, https://gyazo.com/ea18e6f50ae83a44d274e8cf5380cfb9 It causes errors without CommandSender sender...

2017-07-04 10:04 UTC, mayokek commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> +    public static void smite(Player player, CommandSender sender)
@savnith, perhaps you misunderstood what Lemon has said. He said other commands/listeners are using this method and needs to be updated.

2017-07-04 10:13 UTC, JeromSar commented
The remote repository was deleted.

2017-07-04 10:13 UTC, closed without merging