Add /getgamemode
TotalFreedom/TotalFreedomMod pull request #2114
Opened 2017-08-17 02:17 UTC by hitzzaf

Fixes #2113 
Add's /getgamemode.
Aliases: /ggm, /getgm
Permissions: OPs
Description: "Get a players gamemode."
Usage </command> <playername>
Prints out as
"HitzzAF is in gamemode CREATIVE."

2017-08-17 10:42 UTC, lemonsked requested changes

2017-08-17 10:42 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +
useless whitespace.

2017-08-17 10:42 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +@CommandParameters(description = "Get a players gamemode.", usage = "/<command> <playername>", aliases = "getgm,ggm")
Put a space after the comma, please.

2017-08-17 10:42 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +            msg(ChatColor.GRAY + "Player not found!");
Use `msg(FreedomCommand.PLAYER_NOT_FOUND);`

2017-08-17 10:42 UTC, OxLemonxO commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_getgamemode.java
> +        }
Missing return statement, code will continue running even though player is not found.

2017-08-17 11:54 UTC, StevenLawson commented
@hitzzaf Please [create separate branches for each feature](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#quick-guide). This still has old commits for the /savebuild command that you proposed.
![](http://i.imgur.com/EpIaPjG.png)

2018-05-27 12:44 UTC, Wild1145 commented
Thank you for your contribution. Sadly we have decided to close this issue as there has been no recent activity to this pull request. If you wish to continue working on this PR please re-open the issue and ensure that all requested changes are made.

The original issue has also been rejected as an issue.

2018-05-27 12:44 UTC, closed without merging