Fixes /tag clearall
TotalFreedom/TotalFreedomMod pull request #2134
Opened 2017-12-05 05:32 UTC by xensace

https://github.com/TotalFreedom/TotalFreedomMod/issues/2115

2017-12-05 06:05 UTC, Focusvity commented
That doesn't solve the issue.

2017-12-24 14:10 UTC, Wild1145 requested changes

2017-12-24 14:10 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_tag.java
> +                            playerdata.setTag(null);
Setting a tag to null sounds like a really really bad idea...

2017-12-24 14:10 UTC, Wild1145 commented on src/main/java/me/totalfreedom/totalfreedommod/command/Command_tag.java
> +                        // Give the admin their default tag
You never increment the counter, you probably want a player and admin counter if you were to do something like this.

2019-03-17 11:55 UTC, closed without merging